#!/bin/sh

print_ok_message() {
    cat <<EOF
lint-commit-msg: commit message OK
EOF
}

expect_linting_error() {
    exit_code 1
    stdout_contains "ERROR: commit message not properly formatted"
}

expect_user_error() {
    exit_code 2
}

expect_success() {
    exit_code 0
    stderr_empty
    stdout_contains "$(print_ok_message)"
    stdout_not_contains "WARN"
    stdout_not_contains "ERROR"
}

# init_git_repo initializes a Git repository in the working
# directory using configuration that is otherwise arbitrary
# but suppresses warnings and errors in Github CI workflows.
init_git_repo() {
    git -c "init.defaultBranch=main" init &&
        git config user.name "John Doe" &&
        git config user.email "john.doe@example.com" ||
        fail "Failed to initialize git repo"
}
