name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run some diagnostics
        run: |
          echo "Bash version: ${BASH_VERSION}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          grep --version
          sed --version
          uniq --version
          sort --version
          timeout --version
          git --version
          echo "pwd: ${PWD}"
          echo "ls:"
          ls -la

      - name: Run tests
        run: |
          ./run-tests.sh
