name: create-release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Create release upon tag creation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/workflows/create-release.sh
